### ISSUE TITLE
Issue with cdf --help after upgrading past 0.5.20

### ISSUE THREAD

**Issue by benjydp** [cognitedata/toolkit#1586]
Hi!
After upgrading from toolkit version 0.5.20 to 0.5.22, an error is thrown when running cdf --help.
This error persists after upgrading to 0.5.24.

Error thrown:
TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx'

**Comment by benjydp** [comment]
Fixed in version 0.5.28
